import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from "@/components/theme-provider"
import {ClerkProvider} from '@clerk/nextjs'
import {Toaster} from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'GeekyUp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  return (
    
    <ClerkProvider>

<html lang="en">
       
       <body className={inter.className}>
         <div> 
         <ThemeProvider
attribute="class"
defaultTheme="dark"
enableSystem
disableTransitionOnChange
>

       {children}
       </ThemeProvider>
         </div>
       
       </body>
       <Toaster/>
</html>

</ClerkProvider>

    
  )
}


